(in-package :quickhoney)

(defparameter *microspot-names* '("virus-_icons"
                                  "american-artists_neo"
                                  "roxymusic"
                                  "womans_health_qh"
                                  "MensHealth_iconsQH"
                                  "nyt-scholastic-2.TimeQH"
                                  "enterprice-iso-team-1"
                                  "pc-mag-icons1"
                                  "aarp-icons-QH"
                                  "USAguns"
                                  "helloween-neon-ny"
                                  "footballers1"
                                  "QH-BIKE-MERCH"
                                  "Runnersworld-QH"
                                  "okay-2"
                                  "milk-glass-2"
                                  "free-online-poster-small"
                                  "QH-avatars"
                                  "pipe-dream"
                                  "cornwolfneon"
                                  "doomBotusa"
                                  "dr-lv"
                                  "veils-1.1--QH"
                                  "alarm-clocks-QH"
                                  "clown-nothing-shirt2"
                                  "iphone-icons"
                                  "USA-bike-sticker"
                                  "blender-3dcons"
                                  "maxim-icoons-red-old"
                                  "hsbc-bank-pie-illus"
                                  "german-family-bike"
                                  "bstlsexicons"
                                  "maxo3-oldies-"
                                  "travel-12"
                                  "GQoldMIL"
                                  "BLACKSHAPES"
                                  "Bikefamy"
                                  "refreeeset"
                                  "bikers2"
                                  "peekasso-QH1"
                                  "savty-card-QH"
                                  "Moviefatl"
                                  "bmwrainse"
                                  "jerseys"
                                  "bikers1"
                                  "peopleicons3.1"
                                  "blender-prison-icons-portfo"
                                  "Helloween1"
                                  "bmwmagtraffic"
                                  "peopleicons2"
                                  "peopleicons"
                                  "petrydish"
                                  "sexybpattern"
                                  "nycars1"
                                  "applesandos"
                                  "GQhotel"
                                  "tinmericons"
                                  "detailsflight"
                                  "styleguy6"
                                  "styleguy4"
                                  "unterhosegq"
                                  "styleguy3"
                                  "styleguy2"
                                  "styleguy1"
                                  "sexstern"
                                  "sexismallpeople"
                                  "Jailsport"
                                  "maximset2"
                                  "maximset1"
                                  "inflightfront"
                                  "inflightback"
                                  "forgolfersmag"
                                  "espnsport"
                                  "bestliveinstructions"))

(defparameter *honeypen-names* '("Becky_Hinterhof-Iso-877"
                                 "ThingD-Twitter-4_0_QH_flat"
                                 "ThingD-Demon-C-1_1_sm"
                                 "ThingD-Demon-5-A-sm"
                                 "bonus-5"
                                 "bonus-4"
                                 "bonus-7"
                                 "bonus-6"
                                 "bonus-3"
                                 "doodles2"
                                 "bonus-1"))

(defun move-pictures (names new-subcategory)
  (with-transaction ()
    (dolist (name names)
      (let ((image (store-image-with-name name)))
        (if image
            (setf (quickhoney-image-cat-sub image) (list (quickhoney-image-category image) new-subcategory))
            (format t "~A not found~%" name))))))

(defun do-move ()
  (move-pictures *microspot-names* :microspot)
  (move-pictures *honeypen-names* :honeypen))